/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package videojuego;

import java.awt.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;

/**
 *
 * @author Juan
 */
public class MenuNiveles extends javax.swing.JFrame {

    /**
     * Creates new form MenuNiveles
     */
    private Image img;
    public Font letra;
    public int tamaño = 20;
    VentanaJuego ventana;
   
    public MenuNiveles(){
        initComponents();
        estilo();
    }
    
    public MenuNiveles(VentanaJuego ventana) {
        initComponents();
        estilo();
        setSize(450,336);
        this.ventana=ventana;
        
    }
    
    public void estilo(){
        
        ImageIcon z = new ImageIcon("fondos/fondoMenus.png");
        img = z.getImage();
        
         try{
        letra = (Font.createFont(Font.TRUETYPE_FONT, new FileInputStream(new File("Font/001.ttf")))).deriveFont(Font.BOLD,tamaño);
        }catch(IOException | FontFormatException e)
        {
            System.out.println("Error al cargar : " + e.toString());
        }        
        
        nivelUno.setBackground(Color.blue);
        nivelUno.setBorder(BorderFactory.createLineBorder(Color.white));
        nivelUno.setForeground(Color.white);
        nivelUno.setFont(letra);

        nivelDos.setBackground(Color.blue);
        nivelDos.setBorder(BorderFactory.createLineBorder(Color.white));
        nivelDos.setForeground(Color.white);
        nivelDos.setFont(letra);
        
        nivelTres.setBackground(Color.blue);
        nivelTres.setBorder(BorderFactory.createLineBorder(Color.white));
        nivelTres.setForeground(Color.white);
        nivelTres.setFont(letra);
        
        regresar.setBackground(Color.blue);
        regresar.setBorder(BorderFactory.createLineBorder(Color.white));
        regresar.setForeground(Color.white);
        regresar.setFont(letra);
    }
    
    public void paint(Graphics g){
        super.paint(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.drawImage(img, 0, 0, null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nivelTres = new javax.swing.JButton();
        nivelDos = new javax.swing.JButton();
        nivelUno = new javax.swing.JButton();
        regresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        nivelTres.setText("NIVEL 3");
        nivelTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelTresActionPerformed(evt);
            }
        });

        nivelDos.setText("NIVEL 2");
        nivelDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelDosActionPerformed(evt);
            }
        });

        nivelUno.setText("NIVEL 1");
        nivelUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nivelUnoActionPerformed(evt);
            }
        });

        regresar.setText("REGRESAR");
        regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nivelUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nivelDos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nivelTres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(regresar, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE))
                .addGap(0, 38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(nivelUno, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nivelDos, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nivelTres, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(regresar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nivelUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelUnoActionPerformed
        
        int x;
        setVisible(false);
        ventana.juego.sound_player.stop();
        x=ventana.juego.getNivel();
        ventana.juego=null;
        ventana.juego= new Juego(ventana);
        ventana.juego.setHeroe("sonic/", 75, 50, 5);
        ventana.juego.setEscenario("1.gif", 1024, 768);
        ventana.juego.setEnemigo(40);
        ventana.juego.setItem(20);
        ventana.juego.setNivel(x);
        ventana.juego.setMusica(ventana.juego.sonidos[1][1]);
        ventana.juego.sound_player.start();
        ventana.juego.setPausa(false);
        ventana.setVisible(true);
        
    }//GEN-LAST:event_nivelUnoActionPerformed

    private void nivelTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelTresActionPerformed
        
        int x;
        if(ventana.juego.getNivel()>=3){
        
        setVisible(false);
        ventana.juego.sound_player.stop();
        x=ventana.juego.getNivel();
        ventana.juego=null;
        ventana.juego= new Juego(ventana);
        ventana.juego.setHeroe("sonic/", 75, 50, 5);
        ventana.juego.setEscenario("3.png", 1024, 768);
        ventana.juego.setEnemigo(40);
        ventana.juego.setItem(20);
        ventana.juego.setNivel(x);
        ventana.juego.setMusica(ventana.juego.sonidos[1][3]);
        ventana.juego.sound_player.start();
        }
        ventana.juego.setPausa(false);
        ventana.setVisible(true);
      
        
    }//GEN-LAST:event_nivelTresActionPerformed

    private void regresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regresarActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        ventana.menu.setVisible(true);
    }//GEN-LAST:event_regresarActionPerformed

    private void nivelDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nivelDosActionPerformed
       
        int x;
        if(ventana.juego.getNivel()>=2){
            
        ventana.juego.sound_player.stop();
        x=ventana.juego.getNivel();
        ventana.juego=null;
        ventana.juego= new Juego(ventana);
        ventana.juego.setHeroe("sonic/", 75, 50, 5);
        ventana.juego.setEscenario("2.png", 1024, 768);
        ventana.juego.setEnemigo(40);
        ventana.juego.setItem(20);
        ventana.juego.setNivel(x);
        ventana.juego.setMusica(ventana.juego.sonidos[1][2]);    
        ventana.juego.sound_player.start();
        
        }
       setVisible(false);
       ventana.juego.setPausa(false);
       ventana.setVisible(true);
    }//GEN-LAST:event_nivelDosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        
        
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuNiveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuNiveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuNiveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuNiveles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MenuNiveles().setVisible(true);
            }
        });
        
                  
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton nivelDos;
    private javax.swing.JButton nivelTres;
    private javax.swing.JButton nivelUno;
    private javax.swing.JButton regresar;
    // End of variables declaration//GEN-END:variables
}
