/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package videojuego;

import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.*;
import java.io.*;
import java.util.*;

/**
 *
 * @author Marco David
 */
public class VentanaJuego extends javax.swing.JFrame implements KeyListener, ActionListener, Runnable, Serializable{
    
    
    Juego juego;
    MenuInicio menu;
    MenuNiveles niveles;
    MenuPausa pausar;
    LinkedList highScore= new LinkedList();
    
    public VentanaJuego() {
        initComponents();
        juego= new Juego(this);
        createBufferStrategy(2);
        addKeyListener(this);
        juego.setHeroe("sonic/", 75, 50, 5);
        juego.setEscenario("1.gif", 1024, 768);
        juego.setEnemigo(40);
        juego.setItem(20);
        juego.setMusica(juego.sonidos[1][1]);
        menu= new MenuInicio(this);
        niveles= new MenuNiveles(this);
        pausar = new MenuPausa(this);
        this.setIconImage(new ImageIcon("fondos/icono.png").getImage());
      
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
     public void paint(Graphics g) {
        //super.paint(g);
       juego.actualiza();
    }
     
     public void escribirScore(String nuevo){
         
         int i=0;
         String s, f[], g[];
         while(i<highScore.size()){
             f=nuevo.split(" ");
             g=((String)highScore.get(i)).split(" ");
             if(highScore.get(i)==null || Integer.parseInt(f[1])> Integer.parseInt(g[1])){
                 highScore.add(i, nuevo);
                 break;
             }
             
             i++;
         }
         
         if(highScore.size()>50){
             highScore.removeLast();
         }
         
         try{
         ObjectOutputStream escribe= new ObjectOutputStream(new FileOutputStream("scores.dat"));
         escribe.writeObject(highScore);
         escribe.close();
         
         
         }catch(IOException ioe){
             System.out.println(ioe.getMessage());
         }
         
     }
     
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jugar = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        configuraciones = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sonic Runner!");

        jMenu1.setText("File");

        jugar.setText("Jugar");
        jMenu1.add(jugar);

        Salir.setText("jMenuItem1");
        jMenu1.add(Salir);

        jMenuBar1.add(jMenu1);

        configuraciones.setText("Configuraciones");
        configuraciones.add(jMenuItem1);

        jMenuItem2.setText("jMenuItem2");
        configuraciones.add(jMenuItem2);

        jMenuItem3.setText("jMenuItem3");
        configuraciones.add(jMenuItem3);

        jMenuBar1.add(configuraciones);

        jMenu3.setText("Niveles");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new VentanaJuego().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Salir;
    private javax.swing.JMenu configuraciones;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jugar;
    // End of variables declaration//GEN-END:variables

@Override
    public void keyTyped(KeyEvent e) {
        
    }

    @Override
    public void keyPressed(KeyEvent e) {
        juego.accion(e.getKeyCode());
    }

    @Override
    public void keyReleased(KeyEvent e) {
       juego.desaccion(e.getKeyCode());
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
        throw new UnsupportedOperationException("Not supported yet.");
    }

    @Override
    public void run() {
        throw new UnsupportedOperationException("Not supported yet.");
    }

}
